project:
  type: website
  output-dir: docs

website:
  title: "MIDSEA ECR"
  navbar:
    title: "<span class='logo-ecr'>MIDSEA</span><span class='logo-line'></span><span class='logo-ecr'>ECR</span>"
    background: light
    left:
      - text: Home
        href: index.qmd
      - text: News
        href: news.qmd
      - text: People
        href: people.qmd
      - text: Gallery
        href: gallery.qmd
      - text: Blog
        href: blog.qmd

format:
  html:
    theme: [zephyr, custom.scss]
    css: styles.css
    toc: true



