project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-NYC0VGZH85"
  title: "MIDSEA ECR"
  navbar:
    title: "<span class='logo-ecr'>MIDSEA</span><span class='logo-line'></span><span class='logo-ecr'>ECR</span>"
    background: light
    left:
      - text: News
        href: news.qmd
      - text: People
        href: people.qmd
      - text: Mentorship
        href: mentor.qmd
      - text: Monthly meetings
        href: meeting.qmd
      - text: Materials
        href: mat.qmd
      - text: Gallery
        href: gallery.qmd
      - text: Blog
        href: blog.qmd

format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css

comments:
  giscus:
    repo: midsea-ecr/midsea-ecr.github.io

